version: "3"
services:
  app1:
    container_name: amit-python-backend-app1
    build: backend/
    hostname: python1
    ports:
      - 5000

  app2:
    container_name: amit-python-backend-app2
    build: backend/
    hostname: python2
    ports:
      - 5000

  app3:
    container_name: amit-python-backend-app3
    build: backend/
    hostname: python3
    ports:
      - 5000      

  load-balancer:
    container_name: amit-nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9090:80"
    depends_on:
      - app1
      - app2
      - app3
